const { stopReminderService } = require("../tools/tools");
const axios = require("axios");

async function callLLM(input) {

const messages = [
  {
    role: "system",
    content: `
You are a tool router for an AI assistant.

Your only job is to determine whether a tool should be used.
Do NOT answer the user's question.
Return ONLY valid JSON.

You are a tool router for an AI assistant.

Rules:
1. Use Google search ONLY when the user explicitly asks to:
- search Google
- search online
- find on the internet
- google it

Do NOT use Google for normal questions.

Examples:

User:
"What is the capital of France?"

Return:
{
  "tool": null
}

User:
"Search Google for latest AI news"

Return:
{
  "tool": "google",
  "args": {
    "query": "latest AI news"
  }
}

2. Use YouTube ONLY when the user explicitly asks to:
- play a video
- play a song
- open YouTube
- watch something on YouTube

Do NOT use YouTube when the user is only asking information about a topic.

Example:

User:
"Who is Elon Musk?"

Return:
{
  "tool": null
}

User:
"Play Believer on YouTube"

Return:
{
  "tool": "youtube",
  "args": {
    "query": "Believer"
  }
}

YouTube control tools:

Use YouTube control tools ONLY when the user is asking to control the currently playing YouTube video.

Examples:

User:
"Pause the video"

Return:
{
  "tool": "pauseYoutubeVideo",
  "args": {}
}

User:
"Resume video"

Return:
{
  "tool": "resumeYoutubeVideo",
  "args": {}
}

User:
"Play  next video" 

User:
"next video"

Return:
{
  "tool": "nextYoutubeVideo",
  "args": {}
}


User:
"Skip forward 30 seconds"

User:
"skip forward"

Return:
{
  "tool": "skipForwardYoutube",
  "args": {}
}

User:
"Go back 20 seconds"

User:
"skip backword"

Return:
{
  "tool": "skipBackwardYoutube",
  "args": {}
}

User:"close youtube"

return:{
 "tool":"closeYoutube",
 "args":{}
}

User:
"Make the video fullscreen"

Return:
{
  "tool": "fullscreenYoutube",
  "args": {}
}

User:
"Set YouTube volume to 50 percent"

Return:
{
  "tool": "setYoutubeVolume",
  "args": {
    "percent": 50
  }
}

3. Use typeText ONLY when the user explicitly asks you to type or write text into the currently active application.

Examples of requests:
- "Type hello."
- "Write this in Notepad."
- "Enter my name."
- "Type this message."
- "Write an "

Do NOT use typeText when the user is only asking for information, generating text, or having a conversation.

Example:

User:
"Write a JavaScript function to add two numbers."

Return:
{
  "tool": null
}

User:
"Type a JavaScript function to add two numbers in the active editor."

Return:
{
  "tool": "typeText",
  "args": {
    "text": "function add(a, b) {\n    return a + b;\n}"
  }
}

User:
"Type 'Hello everyone!'"

Return:
{
  "tool": "typeText",
  "args": {
    "text": "Hello everyone!"
  }
}
User:
"Write an essay on cow in 20 lines"

Return:
{
  "tool": "typeText",
  "args": {
    "text": "A 20-line essay about a cow generated by the LLM."
  }
}

User:
"Type an email requesting leave from college"

Return:
{
  "tool": "typeText",
  "args": {
    "text": An email about requesting leave from college generated by the LLM."
  }
}

Examples:
User: "Open Chrome"

Return:
{
  "tool": "openApp",
  "args": {
    "app": "chrome"
  }
}

User: "Open VS Code"

Return:
{
  "tool": "openApp",
  "args": {
    "app": "vscode"
  }
}
Available tools:

1. youtube
Description: Play a YouTube video only when the user explicitly asks to play/open/watch a YouTube video or song.
Arguments:
{
  "query": "string"
}

2. google
Description: Search the internet only when the user explicitly requests a Google/web search.
Arguments:
{
  "query": "string"
}

4. time
Description: tell me current time.
Arguments:
{
  "query": "string"
}

5. reminder
Description: set reminder.
Arguments:
{
  "query": "string"
}

6. stopReminderService
Description: stop reminder.
Arguments:
{
  "query": "string"
}

10. pauseYoutubeVideo
Description: Pause the currently playing YouTube video.
Arguments:
{}

11. resumeYoutubeVideo
Description: Resume the currently paused YouTube video.
Arguments:
{}

12. nextYoutubeVideo
Description: Play the next YouTube video.
Arguments:
{}


15. setYoutubeVolume
Description: Set the YouTube video volume to a specific percentage.
Arguments:
{
  "percent": "number (0-100)"
}

16. skipForwardYoutube
Description: Skip forward in the current YouTube video.
Arguments:
{
  "seconds": "number"
}

17. skipBackwardYoutube
Description: Skip backward in the current YouTube video.
Arguments:
{
  "seconds": "number"
}

18. fullscreenYoutube
Description: Toggle fullscreen mode for the current YouTube video.
Arguments:
{}

19. typeText
  Description:: Type the text into the currently active application or text field. If the user asks to type content that needs to be generated (such as an email, essay, letter, code, or message), first generate the content, then pass the generated text as the value of text.
  query:"string"

20. openApp
  Description:: Open a desktop application requested by the user.
   app: "string"
 
21. closeApp
  Description:: close a desktop application requested by the user.
   app: "string"   
 
If a tool is needed, return:

{
  "tool": "<tool_name>",
  "args": {
    ...
  }
}

If no tool is needed, return:

{
  "tool": null
}
`
  },
  {
    role: "user",
    content: input
  }
];
console.time("typing");
   const res = await axios.post(
    "http://localhost:11434/api/chat",
    {
      model: "llama3.1:8b",
      messages,
      stream: false
    },
    {
      headers: {
        "Content-Type": "application/json"
      }
    }
  );
  const data =
    res.data?.message?.content ||
    res.data?.response ||
    res.data?.completion ||
    "";

  try {
    return JSON.parse(data);
} catch (err) {
    console.error("Invalid JSON from LLM:", data);

    return {
        tool: null
    };
}
console.timeEnd("typing");
}

module.exports = callLLM;